from pydantic import BaseModel
from typing import Literal
from datetime import datetime, timedelta
from utils.llm_models import Model

class ResponseModel(BaseModel):
    """
    Represents a single response generated by an LLM agent when a prompt is presented to it.

    Attributes:
        type (Literal): The type of agent sending the response (either 'Evaluator' or 'Grader').
        model (Model): The model of said agent.
        content (str): The content of the response in JSON.
        time_requested (datetime): The timestamp when the response is generated.
        time_completed (datetime): The timestamp when the response was completed.
        time_taken (datetime.timedelta): The time it took for the response to process.
    """
    type: Literal["Evaluator", "Grader"]
    model: Model
    content: str
    time_requested: datetime
    time_completed: datetime
    time_taken: timedelta